import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "../context/authContext";
import { WalletContextProvider } from "../context/walletContext";
import { DidContextProvider } from "../context/DidContext";
import ToasterWrapper from "../components/toasts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletContextProvider>
          <DidContextProvider>
            <AuthContextProvider>
              <ToasterWrapper />
              {children}
            </AuthContextProvider>
          </DidContextProvider>
        </WalletContextProvider>
      </body>
    </html>
  );
}
